//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS2Zoho.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"NY09(?<transaction_type>\d{2})30(?<transaction_number>\d{7})(?<date_day>\d{2})(?<date_month>\d{2})(?<date_year>\d{2})(?<centre_id>\d{2})(?<day_code>\d{2})(?<partial_settlement_number>\d{1})(?<serial_number>\d{5})(?<sign>[\d-])0+(?<amount>\d+)(?<amount_ore>\d{2})\s+(?<KID>[\d]+)\d\d{6}[\r\n]{1,2}NY09(?<transaction_type_2>\d{2})31(?<transaction_number_2>\d{7})(?<form_number>\d{10})(?<agreement>\d{9})0{7}(?<bank_date>\d{6})(?<debit_account>\d{11})0{22}[\r\n]{1,2}")]
        public string InputRegex {
            get {
                return ((string)(this["InputRegex"]));
            }
            set {
                this["InputRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Payment Number\",\"Date\",\"Exchange Rate\",\"Amount\",\"Description\",\"Invoice Number\",\"" +
            "Invoice Amount\",\"Mode\"")]
        public string OutputHeader {
            get {
                return ((string)(this["OutputHeader"]));
            }
            set {
                this["OutputHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#i#,{date_day}/{date_month}/{date_year},1.000,{amount}.{amount_ore},{debit_accoun" +
            "t},{KID},{amount}.{amount_ore},Bank Remittance")]
        public string OutputLine {
            get {
                return ((string)(this["OutputLine"]));
            }
            set {
                this["OutputLine"] = value;
            }
        }
    }
}
